# Generated by Django 5.1.1 on 2024-09-05 07:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='images',
        ),
        migrations.AddField(
            model_name='tour',
            name='available_dates',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tour',
            name='booking_conditions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tour',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='meeting_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='organizational_details',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='tour_description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='tour',
            name='short_description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tour',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
