# Generated by Django 5.1.1 on 2024-09-05 09:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_tour_images_tour_available_dates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='booking_conditions',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='date',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='meeting_place',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='tour_description',
        ),
        migrations.AlterField(
            model_name='tour',
            name='route',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
