# Generated by Django 5.1.1 on 2024-09-06 13:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_tour_booking_conditions_remove_tour_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='expectations',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
