# Generated by Django 5.1.1 on 2024-09-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_tour_expectations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='tour',
            name='route',
        ),
        migrations.AddField(
            model_name='tour',
            name='tags',
            field=models.ManyToManyField(related_name='tours', to='blog.tag'),
        ),
    ]
