# Generated by Django 5.1.1 on 2024-10-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_tag_remove_tour_route_tour_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='tour_type',
            field=models.CharField(choices=[('bike', 'Na rowerze'), ('car', 'Na maszynie'), ('other', 'Inny transport')], default='other', max_length=10),
        ),
    ]
