# Generated by Django 5.1.1 on 2024-10-16 11:31

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_tour_tour_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='tags',
        ),
        migrations.AddField(
            model_name='tour',
            name='extra_charges',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='included_in_price',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='notes',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_type',
            field=models.CharField(choices=[('bike', 'На вело'), ('car', 'На машине'), ('other', 'Иной странспорт'), ('walk', 'Пешком'), ('boat', 'На лодке')], default='other', max_length=10),
        ),
    ]
